In [62]:
import numpy as np

In [63]:
a= [1,2,3,4]
npa = np.array(a, dtype = np.float32) # type을 float32로

print(a)
print(npa) # numpy의 array, 표현하는 방법이 조금 다르다 -> 좋은 도구를 쓴다고 생각!

[1, 2, 3, 4]
[1. 2. 3. 4.]


In [64]:
npa

array([1., 2., 3., 4.], dtype=float32)

In [65]:
npa.dtype # 어떤 자료형으로 만들어졌는지

dtype('float32')

In [66]:
d= [ [1,2,3],[4,5,6],[7,8,9]]
npd = np.array(d)

In [67]:
print(npd.ndim) # 차원
print(npd.shape)
npd

2
(3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
npe = np.empty([7, 5]) # 7x5 행렬인데 empty한 상태로(비워져 있는 상태로)
npe = np.zeros([7, 5], dtype=np.int32) # 모든 원소 0
npe = np.ones([7, 5], dtype=np.int32) # 모든 원소 1
npe

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [69]:
npe = np.zeros([7, 5], dtype=np.int32) # 7 x 5, type= 0으로 초기화 해달라
npe

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [70]:
f = range(1, 10)
npf = np.arange(1, 10)
npf = np.arange(1, 10, 2)
npf

array([1, 3, 5, 7, 9])

In [71]:
npg = np.linspace(0, 10, num=4,endpoint = False) #간격을 최대한 유사하게 # endpoint는 소수점 지저분한거 지움
npg

array([0. , 2.5, 5. , 7.5])

In [72]:
nph = np.arange(10)
print(nph[4]) # indexing, 단일값
print(nph[2:5])
print(nph[2:])
print(nph[:])
print(nph[::3])

4
[2 3 4]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


In [73]:
nph[:3] = [10, 20, 30] # nph는 원본 데이터가 바뀌지 않음 (0~9에서 0,1,2만 바뀌고 나머지 그대로) / 원래같았으면 10,20,30

In [74]:
nph

array([10, 20, 30,  3,  4,  5,  6,  7,  8,  9])

In [75]:
#h = [ [1,2,3,4],[5,6,7,8],[9,10,11,12] ]
#nph = np.array(h)
nph = np.arange(1,13).reshape( (3,4) ) # 3행 4열로 만들어 주세요
nph[1]
#nph[0:2]
#nph[1][1] 
#nph[1,2] #1행 2열, [][]과 비슷하지만 행렬처럼 들어간다
nph[:2, 2:]
nph[:, 3] # 행은 다이면서 열은 3열

array([ 4,  8, 12])

In [76]:
npi = np.arange(1, 13)
print(npi[1])
print(npi[2:5])
print(npi[[0, 4, 6, 9]]) # 여러개의 원소 뽑아오기

2
[3 4 5]
[ 1  5  7 10]


In [84]:
npi = np.arange(1, 13).reshape((4,3)) # 4행 3열, 2차원
npi

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
rows = np.array([0, 0, 3, 3]) # rows의 차원 # 위치값을 리스트로 주는 것과 같다 
cols = np.array([0, 2, 0, 2]) # 0행 0열, 0행 2열, 3행 0열, 3행 2열
npi[rows,cols] # 1차원이면 rows만, 2차원이므로 cols도 주기

array([ 1,  3, 10, 12])

In [81]:
rows = np.array([[0, 0], [3,3]]) # 2차원이므로 [[]]
cols = np.array([[0,2], [0,2]])
npi[rows, cols]

array([[ 1,  3],
       [10, 12]])

In [85]:
npj = np.arange(10)
npj

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
npj < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [86]:
npj[npj <5 ]

array([0, 1, 2, 3, 4])

In [91]:
npj[[True,True, False, True, 
     False, True,False, True, False, False]] # true면 나옴

array([0, 1, 3, 5, 7])

In [93]:
npk = np.array([1, 2, np.nan, 4, 5, np.nan, 6]) #nan = 결측치 처리, not a number
print(npk)
print(npk[np.isnan(npk)]) # nan 들어있느냐
print(npk[~np.isnan(npk)]) # not nan 뽑기

[ 1.  2. nan  4.  5. nan  6.]
[nan nan]
[1. 2. 4. 5. 6.]


In [96]:
npl = np.arange(10)
# npl
npl + 5 # npl + ([5] * 10 -> [5,5,5,5,5,5,5,5,5,5,5,5])과 같다

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
a+b


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [169]:
np.arange(1, 10, 2)
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
# 4열~ 52열까지의 데이터를 읽어서 Numpy 배열로 만드세요
import csv

with open('data-files/subway-data.csv', encoding='utf-8') as f:
    reader = csv.reader(f)
    next(reader)
    next(reader)
    
import numpy as np
frow = row[4:52]
print(frow)
floatrow= np.array(frow)
print(floatrow)

['620', '13', '13,095', '2,198', '9,135', '7,173', '11,941', '12,507', '17,471', '25,104', '16,819', '23,527', '16,366', '22,714', '17,629', '25,220', '21,258', '25,909', '22,664', '24,403', '23,524', '23,966', '24,632', '22,634', '25,447', '19,352', '25,133', '19,093', '24,186', '18,922', '16,973', '20,328', '13,729', '14,643', '13,253', '10,925', '10,893', '10,333', '4,659', '10,298', '25', '1,012', '0', '0', '0', '0', '0', '0']
['620' '13' '13,095' '2,198' '9,135' '7,173' '11,941' '12,507' '17,471'
 '25,104' '16,819' '23,527' '16,366' '22,714' '17,629' '25,220' '21,258'
 '25,909' '22,664' '24,403' '23,524' '23,966' '24,632' '22,634' '25,447'
 '19,352' '25,133' '19,093' '24,186' '18,922' '16,973' '20,328' '13,729'
 '14,643' '13,253' '10,925' '10,893' '10,333' '4,659' '10,298' '25'
 '1,012' '0' '0' '0' '0' '0' '0']


In [159]:
# 선생님
with open('data-files/subway-data.csv', encoding='utf-8') as f:
    reader = csv.reader(f)
    
    subway_data_list

In [ ]:
subway_data_list[2]

In [161]:
import numpy as np
subway_data_array = np.array(subway_data_list[2:])

In [162]:
print(subway_data_array.ndim)
print(subway_data_array.shape)
subway_data_array[:2]
subway_data_array2 = subway_data_array[:, 4:-1] # 행, 열
subway_data_array2[:2]

2
(597, 53)


array([['813', '16', '8,478', '5,920', '10,736', '37,191', '29,922',
        '80,358', '53,921', '170,533', '39,251', '114,126', '38,103',
        '55,958', '46,762', '47,869', '55,232', '49,303', '57,055',
        '51,283', '48,828', '49,860', '64,421', '50,831', '71,948',
        '51,102', '115,171', '60,380', '176,221', '63,184', '86,920',
        '45,583', '61,811', '31,079', '59,285', '25,122', '41,290',
        '18,647', '15,258', '10,959', '11', '1,427', '0', '0', '0', '0',
        '0', '0'],
       ['30', '1', '1,557', '3,131', '2,914', '15,686', '5,627',
        '57,041', '6,957', '138,115', '7,841', '67,596', '8,553',
        '27,971', '12,095', '26,249', '13,668', '22,574', '17,272',
        '22,013', '22,049', '18,517', '28,018', '16,094', '32,000',
        '13,771', '59,053', '14,576', '115,293', '15,487', '46,640',
        '7,610', '34,966', '4,267', '34,047', '3,807', '22,202', '2,630',
        '7,325', '1,755', '5', '143', '0', '1', '0', '1', '0', '0']],
      dtype='<U

In [ ]:
# !pip install pandas

In [177]:
import csv

with open('data-files/subway-data.csv', encoding="utf-8") as f:
    reader = csv.reader(f)
    next(reader)
    next(reader)
    
    with open('data-files/subway-data-modified.csv', 'w', encoding="utf-8") as f2:        
        for idx, row in enumerate(reader):
            row2 = map(lambda x: x.replace(",", ""), row)
            f2.write(",".join(list(row2)))
            f2.write('\n')
            

In [179]:
import numpy as np

ar = np.genfromtxt('data-files/subway-data-modified.csv', delimiter= ',', encoding= 'utf-8', dtype='U')
ar

array([['2020-05', '1호선', '0150', ..., '0', '0', '2020-06-03 11:49:09'],
       ['2020-05', '1호선', '0151', ..., '0', '0', '2020-06-03 11:49:09'],
       ['2020-05', '1호선', '0152', ..., '0', '0', '2020-06-03 11:49:09'],
       ...,
       ['2020-05', '우이신설선', '4711', ..., '0', '0', '2020-06-03 11:49:09'],
       ['2020-05', '우이신설선', '4712', ..., '0', '0', '2020-06-03 11:49:09'],
       ['2020-05', '우이신설선', '4713', ..., '0', '0', '2020-06-03 11:49:09']],
      dtype='<U19')

In [180]:
ar[:, 4:-1]

array([['813', '16', '8478', ..., '0', '0', '0'],
       ['30', '1', '1557', ..., '1', '0', '0'],
       ['75', '4', '3014', ..., '1', '0', '0'],
       ...,
       ['11', '1', '748', ..., '0', '0', '0'],
       ['2', '0', '350', ..., '0', '0', '0'],
       ['20', '0', '892', ..., '0', '0', '0']], dtype='<U19')

In [165]:
import pandas as pd

In [167]:
df = pd.read_csv('data-files/subway-data.csv', encoding ='utf-8', skiprows=2)

In [168]:
df.head() # 표 형식으로 가져오기

2020-05  1호선  0150   서울역  813  16   8,478  5,920 10,736  37,191  ...  \
0  2020-05  1호선   151    시청   30   1   1,557  3,131  2,914  15,686  ...   
1  2020-05  1호선   152    종각   75   4   3,014  4,160  3,319  23,724  ...   
2  2020-05  1호선   153  종로3가  201  22   4,118  2,484  3,435  12,520  ...   
3  2020-05  1호선   154  종로5가   29   1   1,708  3,562  2,587  15,233  ...   
4  2020-05  1호선   155   동대문  620  13  13,095  2,198  9,135   7,173  ...   

   10,959  11  1,427  0 0.1 0.2 0.3 0.4 0.5  2020-06-03 11:49:09  
0   1,755   5    143  0   1   0   1   0   0  2020-06-03 11:49:09  
1   2,735  58    161  0   0   0   1   0   0  2020-06-03 11:49:09  
2   3,525  53    698  0   0   0   0   0   0  2020-06-03 11:49:09  
3   2,131  15    290  0   1   0   0   0   0  2020-06-03 11:49:09  
4  10,298  25  1,012  0   0   0   0   0   0  2020-06-03 11:49:09  

[5 rows x 53 columns]